import { ImportTemplate, ImportTemplateConfig } from './types.js';

export const IMPORT_TEMPLATES_CONFIG: Record<ImportTemplate, ImportTemplateConfig> = {
  CUSTOMERS: {
    template: 'CUSTOMERS',
    nameAr: 'بيانات العملاء',
    nameEn: 'Customers Master Data',
    category: 'MASTER_DATA',
    descriptionAr: 'استيراد العملاء مع التحقق من الرقم الضريبي (15 خانة) والسجل التجاري وأرقام الجوال السعودية',
    descriptionEn: 'Import customers with 15-digit VAT, Commercial Registration, and Saudi mobile validation',
    primaryKeyField: 'vatNumber',
    secondaryKeyFields: ['mobile', 'code'],
    fields: [
      {
        field: 'nameAr',
        labelAr: 'اسم العميل (عربي)',
        labelEn: 'Customer Name (AR)',
        required: true,
        dataType: 'string',
        example: 'شركة التقنية المتقدمة للتجارة',
        descriptionAr: 'اسم المنشأة أو الفرد بالعربية',
        descriptionEn: 'Customer organization or individual name in Arabic',
        aliases: ['nameAr', 'name_ar', 'اسم العميل', 'الاسم بالعربي', 'Customer Name', 'Name (Arabic)'],
      },
      {
        field: 'nameEn',
        labelAr: 'اسم العميل (إنجليزي)',
        labelEn: 'Customer Name (EN)',
        required: false,
        dataType: 'string',
        example: 'Advanced Tech Trading Co.',
        descriptionAr: 'الاسم بالإنجليزية (اختياري)',
        descriptionEn: 'Customer name in English (optional)',
        aliases: ['nameEn', 'name_en', 'الاسم بالانجليزي', 'English Name', 'Name (English)'],
      },
      {
        field: 'vatNumber',
        labelAr: 'الرقم الضريبي (15 رقم)',
        labelEn: 'VAT Number (15 digits)',
        required: false,
        dataType: 'vat',
        example: '300012345600003',
        descriptionAr: 'الرقم الضريبي المكون من 15 خانة يبدأ وينتهي بـ 3',
        descriptionEn: '15-digit Saudi VAT ID starting and ending with 3',
        aliases: ['vatNumber', 'vat_number', 'الرقم الضريبي', 'VAT Number', 'Tax ID', 'VAT ID'],
      },
      {
        field: 'crNumber',
        labelAr: 'السجل التجاري (10 أرقام)',
        labelEn: 'CR Number (10 digits)',
        required: false,
        dataType: 'string',
        example: '1010987654',
        descriptionAr: 'رقم السجل التجاري المكون من 10 خانات',
        descriptionEn: '10-digit Commercial Registration number',
        aliases: ['crNumber', 'cr_number', 'السجل التجاري', 'CR Number', 'Commercial Registration'],
      },
      {
        field: 'mobile',
        labelAr: 'رقم الجوال السعودي',
        labelEn: 'Saudi Mobile Number',
        required: true,
        dataType: 'mobile',
        example: '0501234567',
        descriptionAr: 'رقم الجوال بصيغة 05XXXXXXXX أو +9665XXXXXXXX',
        descriptionEn: 'Saudi mobile phone (05XXXXXXXX or +9665XXXXXXXX)',
        aliases: ['mobile', 'phone', 'رقم الجوال', 'الجوال', 'الهاتف', 'Mobile Phone', 'Phone Number'],
      },
      {
        field: 'email',
        labelAr: 'البريد الإلكتروني',
        labelEn: 'Email Address',
        required: false,
        dataType: 'email',
        example: 'billing@advtech.sa',
        descriptionAr: 'البريد الإلكتروني للفواتير والتواصل',
        descriptionEn: 'Billing and contact email address',
        aliases: ['email', 'البريد الالكتروني', 'الإيميل', 'Email'],
      },
      {
        field: 'creditLimitSar',
        labelAr: 'الحد الائتماني (ر.س)',
        labelEn: 'Credit Limit (SAR)',
        required: false,
        dataType: 'number',
        example: 50000,
        descriptionAr: 'سقف الائتمان المسموح به بالريال السعودي',
        descriptionEn: 'Maximum allowed credit limit in SAR',
        aliases: ['creditLimitSar', 'creditLimit', 'credit_limit', 'الحد الائتماني', 'Credit Limit'],
      },
      {
        field: 'city',
        labelAr: 'المدينة',
        labelEn: 'City',
        required: false,
        dataType: 'string',
        example: 'الرياض',
        descriptionAr: 'المدينة (العنوان الوطني)',
        descriptionEn: 'City according to national address',
        aliases: ['city', 'المدينة', 'City'],
      },
      {
        field: 'district',
        labelAr: 'الحي',
        labelEn: 'District',
        required: false,
        dataType: 'string',
        example: 'العليا',
        descriptionAr: 'اسم الحي',
        descriptionEn: 'District / Neighborhood',
        aliases: ['district', 'الحي', 'District'],
      },
    ],
    sampleRows: [
      {
        nameAr: 'شركة الرياض للحلول الرقمية',
        nameEn: 'Riyadh Digital Solutions LLC',
        vatNumber: '300012345600003',
        crNumber: '1010567890',
        mobile: '0501112233',
        email: 'finance@riyadhdigital.sa',
        creditLimitSar: 75000,
        city: 'الرياض',
        district: 'الملز',
      },
      {
        nameAr: 'مؤسسة أفق النخبة للتجارة',
        nameEn: 'Horizon Elite Trading Est',
        vatNumber: '310098765400003',
        crNumber: '1010887766',
        mobile: '0559988776',
        email: 'contact@elitetrading.sa',
        creditLimitSar: 30000,
        city: 'جدة',
        district: 'الروضة',
      },
    ],
  },

  SUPPLIERS: {
    template: 'SUPPLIERS',
    nameAr: 'بيانات الموردين',
    nameEn: 'Suppliers Master Data',
    category: 'MASTER_DATA',
    descriptionAr: 'استيراد الموردين مع التحقق من الرقم الضريبي وحساب الآيبان البنكي وأرقام الجوال',
    descriptionEn: 'Import suppliers with VAT number, IBAN bank account, and mobile validation',
    primaryKeyField: 'vatNumber',
    secondaryKeyFields: ['mobile', 'code'],
    fields: [
      {
        field: 'nameAr',
        labelAr: 'اسم المورد (عربي)',
        labelEn: 'Supplier Name (AR)',
        required: true,
        dataType: 'string',
        example: 'شركة التوريدات العالمية المحدودة',
        descriptionAr: 'اسم المورد باللغة العربية',
        descriptionEn: 'Supplier name in Arabic',
        aliases: ['nameAr', 'name_ar', 'اسم المورد', 'الاسم بالعربي', 'Supplier Name'],
      },
      {
        field: 'nameEn',
        labelAr: 'اسم المورد (إنجليزي)',
        labelEn: 'Supplier Name (EN)',
        required: false,
        dataType: 'string',
        example: 'Global Supplies Co.',
        descriptionAr: 'الاسم بالإنجليزية',
        descriptionEn: 'Supplier name in English',
        aliases: ['nameEn', 'name_en', 'الاسم بالانجليزي', 'English Name'],
      },
      {
        field: 'vatNumber',
        labelAr: 'الرقم الضريبي (15 رقم)',
        labelEn: 'VAT Number (15 digits)',
        required: false,
        dataType: 'vat',
        example: '300098765400003',
        descriptionAr: 'الرقم الضريبي السعودي (15 خانة)',
        descriptionEn: '15-digit Saudi VAT ID',
        aliases: ['vatNumber', 'vat_number', 'الرقم الضريبي', 'VAT Number', 'Tax ID'],
      },
      {
        field: 'crNumber',
        labelAr: 'السجل التجاري (10 أرقام)',
        labelEn: 'CR Number (10 digits)',
        required: false,
        dataType: 'string',
        example: '1010456789',
        descriptionAr: 'رقم السجل التجاري',
        descriptionEn: 'Commercial Registration number',
        aliases: ['crNumber', 'cr_number', 'السجل التجاري', 'CR Number'],
      },
      {
        field: 'mobile',
        labelAr: 'رقم الجوال السعودي',
        labelEn: 'Saudi Mobile Number',
        required: true,
        dataType: 'mobile',
        example: '0541234567',
        descriptionAr: 'رقم جوال المورد للتواصل',
        descriptionEn: 'Supplier contact mobile phone',
        aliases: ['mobile', 'phone', 'رقم الجوال', 'الجوال', 'Mobile'],
      },
      {
        field: 'email',
        labelAr: 'البريد الإلكتروني',
        labelEn: 'Email Address',
        required: false,
        dataType: 'email',
        example: 'accounts@globalsupplies.sa',
        descriptionAr: 'البريد الإلكتروني',
        descriptionEn: 'Email address',
        aliases: ['email', 'البريد الالكتروني', 'Email'],
      },
      {
        field: 'bankIban',
        labelAr: 'الآيبان البنكي (SA...)',
        labelEn: 'Bank IBAN (SA...)',
        required: false,
        dataType: 'string',
        example: 'SA0380000000608010167519',
        descriptionAr: 'الآيبان البنكي السعودي للتحويلات',
        descriptionEn: 'Saudi IBAN for supplier payouts',
        aliases: ['bankIban', 'iban', 'الآيبان', 'رقم الحساب البنكي', 'IBAN'],
      },
    ],
    sampleRows: [
      {
        nameAr: 'مصنع الشرق للأخشاب والمواد',
        nameEn: 'Eastern Woods & Materials Factory',
        vatNumber: '300045612300003',
        crNumber: '2050112233',
        mobile: '0548877665',
        email: 'sales@easternwood.sa',
        bankIban: 'SA0380000000608010167519',
      },
    ],
  },

  ITEMS: {
    template: 'ITEMS',
    nameAr: 'أصناف المخزون والخدمات',
    nameEn: 'Inventory Items & Services',
    category: 'MASTER_DATA',
    descriptionAr: 'استيراد دليل الأصناف مع رمز SKU، الباركود، الوحدات، أسعار الشراء والبيع، ونسبة الضريبة',
    descriptionEn: 'Import item catalog with SKU, barcodes, units, purchase/sale pricing, and VAT rate',
    primaryKeyField: 'sku',
    secondaryKeyFields: ['barcode'],
    fields: [
      {
        field: 'sku',
        labelAr: 'رمز الصنف (SKU)',
        labelEn: 'Item SKU Code',
        required: true,
        dataType: 'string',
        example: 'ITM-LAP-001',
        descriptionAr: 'الرمز التعريفي الفريد للصنف',
        descriptionEn: 'Unique Stock Keeping Unit code',
        aliases: ['sku', 'code', 'رمز الصنف', 'كود الصنف', 'Item SKU', 'SKU'],
      },
      {
        field: 'nameAr',
        labelAr: 'اسم الصنف (عربي)',
        labelEn: 'Item Name (AR)',
        required: true,
        dataType: 'string',
        example: 'حاسب محمول للأعمال كور i7',
        descriptionAr: 'اسم الصنف باللغة العربية',
        descriptionEn: 'Item description in Arabic',
        aliases: ['nameAr', 'name_ar', 'اسم الصنف', 'الاسم بالعربي', 'Item Name', 'Description (AR)'],
      },
      {
        field: 'nameEn',
        labelAr: 'اسم الصنف (إنجليزي)',
        labelEn: 'Item Name (EN)',
        required: false,
        dataType: 'string',
        example: 'Business Laptop Core i7',
        descriptionAr: 'الاسم بالإنجليزية',
        descriptionEn: 'Item description in English',
        aliases: ['nameEn', 'name_en', 'الاسم بالانجليزي', 'English Name', 'Item Name (EN)'],
      },
      {
        field: 'category',
        labelAr: 'التصنيف',
        labelEn: 'Category',
        required: false,
        dataType: 'string',
        example: 'ELECTRONICS',
        descriptionAr: 'تصنيف الصنف (أجهزة، قطع غيار، خدمات)',
        descriptionEn: 'Item category',
        aliases: ['category', 'التصنيف', 'الفئة', 'Category'],
      },
      {
        field: 'baseUnit',
        labelAr: 'وحدة القياس الأساسية',
        labelEn: 'Base Unit',
        required: true,
        dataType: 'string',
        example: 'PCS',
        descriptionAr: 'وحدة القياس الأساسية (PCS, KG, BOX, HOUR)',
        descriptionEn: 'Base measurement unit (Rule I4)',
        aliases: ['baseUnit', 'base_unit', 'unit', 'الوحدة', 'وحدة القياس', 'Unit', 'Base Unit'],
      },
      {
        field: 'purchasePrice',
        labelAr: 'سعر الشراء القياسي (ر.س)',
        labelEn: 'Standard Cost (SAR)',
        required: false,
        dataType: 'number',
        example: 3200,
        descriptionAr: 'سعر تكلفة الشراء المعتمد بالريال',
        descriptionEn: 'Standard purchase cost in SAR',
        aliases: ['purchasePrice', 'purchase_price', 'cost', 'سعر التكلفة', 'سعر الشراء', 'Cost Price', 'Purchase Price'],
      },
      {
        field: 'sellingPrice',
        labelAr: 'سعر البيع (ر.س)',
        labelEn: 'Selling Price (SAR)',
        required: true,
        dataType: 'number',
        example: 4100,
        descriptionAr: 'سعر البيع الأساسي غير شامل الضريبة',
        descriptionEn: 'Base selling price exclusive of VAT',
        aliases: ['sellingPrice', 'selling_price', 'price', 'سعر البيع', 'السعر', 'Price', 'Selling Price'],
      },
      {
        field: 'vatRate',
        labelAr: 'نسبة ضريبة القيمة المضافة %',
        labelEn: 'VAT Rate %',
        required: false,
        dataType: 'number',
        example: 15,
        descriptionAr: 'نسبة الضريبة (افتراضياً 15%)',
        descriptionEn: 'Saudi VAT percentage (defaults to 15%)',
        aliases: ['vatRate', 'vat_rate', 'tax_rate', 'نسبة الضريبة', 'ضريبة القيمة المضافة', 'VAT %'],
      },
      {
        field: 'barcode',
        labelAr: 'الباركود',
        labelEn: 'Barcode',
        required: false,
        dataType: 'string',
        example: '6281001234567',
        descriptionAr: 'رمز الباركود الدولي أو الداخلي للوحدة',
        descriptionEn: 'Unit-specific barcode (Rule I4)',
        aliases: ['barcode', 'الباركود', 'Barcode'],
      },
    ],
    sampleRows: [
      {
        sku: 'ITM-ELEC-101',
        nameAr: 'شاشة حاسب آلي 27 بوصة عالية الدقة',
        nameEn: 'Computer Monitor 27-inch 4K',
        category: 'ELECTRONICS',
        baseUnit: 'PCS',
        purchasePrice: 950,
        sellingPrice: 1250,
        vatRate: 15,
        barcode: '6281001234567',
      },
      {
        sku: 'ITM-ELEC-102',
        nameAr: 'لوحة مفاتيح لاسلكية ميكانيكية',
        nameEn: 'Mechanical Wireless Keyboard',
        category: 'ACCESSORIES',
        baseUnit: 'PCS',
        purchasePrice: 180,
        sellingPrice: 260,
        vatRate: 15,
        barcode: '6281007654321',
      },
    ],
  },

  ACCOUNTS: {
    template: 'ACCOUNTS',
    nameAr: 'دليل الحسابات المحاسبي (Chart of Accounts)',
    nameEn: 'Chart of Accounts (CoA)',
    category: 'MASTER_DATA',
    descriptionAr: 'استيراد شجرة الحسابات المحاسبية مع تحديد النوع وطبيعة الرصيد والترتيب الهرمي',
    descriptionEn: 'Import Chart of Accounts with account types, normal balance, and hierarchy',
    primaryKeyField: 'code',
    fields: [
      {
        field: 'code',
        labelAr: 'رقم الحساب',
        labelEn: 'Account Code',
        required: true,
        dataType: 'string',
        example: '10101',
        descriptionAr: 'الرقم الفريد للحساب المحاسبي',
        descriptionEn: 'Unique General Ledger account code',
        aliases: ['code', 'accountCode', 'account_code', 'رقم الحساب', 'كود الحساب', 'Account Code'],
      },
      {
        field: 'nameAr',
        labelAr: 'اسم الحساب (عربي)',
        labelEn: 'Account Name (AR)',
        required: true,
        dataType: 'string',
        example: 'الصندوق الرئيسي - الرياض',
        descriptionAr: 'اسم الحساب باللغة العربية',
        descriptionEn: 'Account name in Arabic',
        aliases: ['nameAr', 'name_ar', 'اسم الحساب', 'الاسم بالعربي', 'Account Name'],
      },
      {
        field: 'nameEn',
        labelAr: 'اسم الحساب (إنجليزي)',
        labelEn: 'Account Name (EN)',
        required: false,
        dataType: 'string',
        example: 'Main Petty Cash - Riyadh',
        descriptionAr: 'الاسم بالإنجليزية',
        descriptionEn: 'Account name in English',
        aliases: ['nameEn', 'name_en', 'الاسم بالانجليزي', 'English Name'],
      },
      {
        field: 'type',
        labelAr: 'نوع الحساب',
        labelEn: 'Account Type',
        required: true,
        dataType: 'string',
        example: 'ASSET',
        descriptionAr: 'أحد الأنواع: ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE',
        descriptionEn: 'ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE',
        aliases: ['type', 'accountType', 'account_type', 'نوع الحساب', 'Type', 'Category'],
      },
      {
        field: 'normalBalance',
        labelAr: 'طبيعة الحساب (DEBIT/CREDIT)',
        labelEn: 'Normal Balance',
        required: false,
        dataType: 'string',
        example: 'DEBIT',
        descriptionAr: 'طبيعة الرصيد: DEBIT (مدين) أو CREDIT (دائن)',
        descriptionEn: 'Normal balance: DEBIT or CREDIT',
        aliases: ['normalBalance', 'normal_balance', 'طبيعة الحساب', 'Normal Balance'],
      },
      {
        field: 'parentCode',
        labelAr: 'رقم الحساب الأب',
        labelEn: 'Parent Account Code',
        required: false,
        dataType: 'string',
        example: '101',
        descriptionAr: 'رقم الحساب الرئيسي في الشجرة',
        descriptionEn: 'Parent account code in CoA tree',
        aliases: ['parentCode', 'parent_code', 'الحساب الأب', 'الحساب الرئيسي', 'Parent Code'],
      },
    ],
    sampleRows: [
      {
        code: '10102',
        nameAr: 'مصرف الراجحي - الحساب التشغيلي',
        nameEn: 'Al Rajhi Bank - Operating',
        type: 'ASSET',
        normalBalance: 'DEBIT',
        parentCode: '101',
      },
      {
        code: '20102',
        nameAr: 'مخصص مكافأة نهاية الخدمة',
        nameEn: 'End of Service Indemnity Provision',
        type: 'LIABILITY',
        normalBalance: 'CREDIT',
        parentCode: '201',
      },
    ],
  },

  OPENING_BALANCES: {
    template: 'OPENING_BALANCES',
    nameAr: 'الأرصدة الافتتاحية لدفتر الأستاذ (Rule G1)',
    nameEn: 'General Ledger Opening Balances',
    category: 'MASTER_DATA',
    descriptionAr: 'استيراد الأرصدة الافتتاحية للحسابات مع التحقق الصارم من التوازن التام (إجمالي المدين = إجمالي الدائن)',
    descriptionEn: 'Import opening balances with strict Rule G1 balancing enforcement (Total Debit == Total Credit)',
    primaryKeyField: 'accountCode',
    fields: [
      {
        field: 'accountCode',
        labelAr: 'رقم الحساب',
        labelEn: 'Account Code',
        required: true,
        dataType: 'string',
        example: '10101',
        descriptionAr: 'رقم الحساب المسجل في دليل الحسابات',
        descriptionEn: 'Valid Chart of Accounts code',
        aliases: ['accountCode', 'account_code', 'code', 'رقم الحساب', 'Account Code'],
      },
      {
        field: 'debitSar',
        labelAr: 'المدين (ر.س)',
        labelEn: 'Debit (SAR)',
        required: false,
        dataType: 'number',
        example: 150000,
        descriptionAr: 'مبلغ المدين بالريال السعودي',
        descriptionEn: 'Debit amount in SAR',
        aliases: ['debitSar', 'debit', 'مدين', 'المدين', 'Debit', 'Debit Amount'],
      },
      {
        field: 'creditSar',
        labelAr: 'الدائن (ر.س)',
        labelEn: 'Credit (SAR)',
        required: false,
        dataType: 'number',
        example: 0,
        descriptionAr: 'مبلغ الدائن بالريال السعودي',
        descriptionEn: 'Credit amount in SAR',
        aliases: ['creditSar', 'credit', 'دائن', 'الدائن', 'Credit', 'Credit Amount'],
      },
      {
        field: 'descriptionAr',
        labelAr: 'البيان (عربي)',
        labelEn: 'Description (AR)',
        required: false,
        dataType: 'string',
        example: 'رصيد افتتاحي للسنة المالية',
        descriptionAr: 'شرح القيد الافتتاحي',
        descriptionEn: 'Opening balance line description',
        aliases: ['descriptionAr', 'description', 'البيان', 'شرح الحساب', 'Description'],
      },
    ],
    sampleRows: [
      {
        accountCode: '10101',
        debitSar: 100000,
        creditSar: 0,
        descriptionAr: 'النقدية بالصندوق - رصيد افتتاحي',
      },
      {
        accountCode: '30101',
        debitSar: 0,
        creditSar: 100000,
        descriptionAr: 'رأس المال المدفوع - رصيد افتتاحي متوازن',
      },
    ],
  },

  SALES_INVOICES: {
    template: 'SALES_INVOICES',
    nameAr: 'حركات فواتير المبيعات (مع البنود)',
    nameEn: 'Sales Invoices & Line Items',
    category: 'MOVEMENTS',
    descriptionAr: 'استيراد فواتير المبيعات وبنودها مجمعة برقم الفاتورة مع التحقق من وجود العميل والأصناف',
    descriptionEn: 'Import sales invoices and lines grouped by invoiceNumber with party & SKU verification',
    primaryKeyField: 'invoiceNumber',
    fields: [
      {
        field: 'invoiceNumber',
        labelAr: 'رقم الفاتورة',
        labelEn: 'Invoice Number',
        required: true,
        dataType: 'string',
        example: 'INV-2026-0001',
        descriptionAr: 'رقم الفاتورة المميز (لتجميع سطور الفاتورة الواحدة)',
        descriptionEn: 'Unique invoice number for grouping lines',
        aliases: ['invoiceNumber', 'invoice_number', 'inv_number', 'رقم الفاتورة', 'Invoice #', 'Invoice Number'],
      },
      {
        field: 'issueDate',
        labelAr: 'تاريخ الفاتورة (YYYY-MM-DD)',
        labelEn: 'Issue Date',
        required: true,
        dataType: 'date',
        example: '2026-03-15',
        descriptionAr: 'تاريخ إصدار الفاتورة بالصيغة القياسية',
        descriptionEn: 'Invoice issue date in YYYY-MM-DD format',
        aliases: ['issueDate', 'issue_date', 'date', 'تاريخ الفاتورة', 'التاريخ', 'Date', 'Issue Date'],
      },
      {
        field: 'customerVatOrMobile',
        labelAr: 'الرقم الضريبي للعميل أو الجوال',
        labelEn: 'Customer VAT or Mobile',
        required: true,
        dataType: 'string',
        example: '300012345600003',
        descriptionAr: 'المفتاح التعريفي للعميل المسجل بالنظام',
        descriptionEn: 'Customer identifier (VAT ID or mobile phone)',
        aliases: ['customerVatOrMobile', 'customerVat', 'customer_vat', 'الرقم الضريبي للعميل', 'جوال العميل', 'Customer VAT', 'Customer'],
      },
      {
        field: 'itemSku',
        labelAr: 'رمز الصنف (SKU)',
        labelEn: 'Item SKU',
        required: true,
        dataType: 'string',
        example: 'ITM-ELEC-101',
        descriptionAr: 'رمز الصنف المباع من دليل الأصناف',
        descriptionEn: 'Existing catalog Item SKU',
        aliases: ['itemSku', 'sku', 'رمز الصنف', 'كود الصنف', 'Item SKU', 'SKU'],
      },
      {
        field: 'quantity',
        labelAr: 'الكمية المباعة',
        labelEn: 'Quantity',
        required: true,
        dataType: 'number',
        example: 2,
        descriptionAr: 'كمية السطر المباعة',
        descriptionEn: 'Line quantity sold',
        aliases: ['quantity', 'qty', 'الكمية', 'العدد', 'Quantity', 'Qty'],
      },
      {
        field: 'unitPrice',
        labelAr: 'سعر الوحدة (ر.س غير شامل الضريبة)',
        labelEn: 'Unit Price (SAR)',
        required: true,
        dataType: 'number',
        example: 1250,
        descriptionAr: 'سعر بيع الحبة قبل الضريبة',
        descriptionEn: 'Unit price exclusive of VAT',
        aliases: ['unitPrice', 'unit_price', 'price', 'السعر', 'سعر الوحدة', 'Unit Price', 'Price'],
      },
      {
        field: 'discountAmount',
        labelAr: 'مبلغ الخصم (ر.س)',
        labelEn: 'Discount Amount (SAR)',
        required: false,
        dataType: 'number',
        example: 0,
        descriptionAr: 'مبلغ الخصم على السطر',
        descriptionEn: 'Line discount amount in SAR',
        aliases: ['discountAmount', 'discount', 'الخصم', 'مبلغ الخصم', 'Discount'],
      },
      {
        field: 'vatRate',
        labelAr: 'نسبة الضريبة %',
        labelEn: 'VAT Rate %',
        required: false,
        dataType: 'number',
        example: 15,
        descriptionAr: 'نسبة ضريبة القيمة المضافة',
        descriptionEn: 'VAT percentage (15%)',
        aliases: ['vatRate', 'vat_rate', 'نسبة الضريبة', 'VAT Rate'],
      },
    ],
    sampleRows: [
      {
        invoiceNumber: 'INV-IMP-1001',
        issueDate: '2026-03-20',
        customerVatOrMobile: '300012345600003',
        itemSku: 'ITM-ELEC-101',
        quantity: 3,
        unitPrice: 1250,
        discountAmount: 0,
        vatRate: 15,
      },
      {
        invoiceNumber: 'INV-IMP-1001',
        issueDate: '2026-03-20',
        customerVatOrMobile: '300012345600003',
        itemSku: 'ITM-ELEC-102',
        quantity: 2,
        unitPrice: 260,
        discountAmount: 20,
        vatRate: 15,
      },
    ],
  },

  PURCHASE_BILLS: {
    template: 'PURCHASE_BILLS',
    nameAr: 'فواتير المشتريات ومصاريف الموردين',
    nameEn: 'Purchase Bills & Vendor Invoices',
    category: 'MOVEMENTS',
    descriptionAr: 'استيراد فواتير المشتريات المعتمدة مع ربطها بالمورد والأصناف وتوليد القيود الآلية',
    descriptionEn: 'Import vendor purchase bills with supplier linking and double-entry accounting',
    primaryKeyField: 'billNumber',
    fields: [
      {
        field: 'billNumber',
        labelAr: 'رقم فاتورة المورد',
        labelEn: 'Bill / Invoice Number',
        required: true,
        dataType: 'string',
        example: 'BILL-SUP-8890',
        descriptionAr: 'رقم الفاتورة الصادرة من المورد',
        descriptionEn: 'Vendor bill or invoice reference number',
        aliases: ['billNumber', 'bill_number', 'bill_no', 'رقم الفاتورة', 'رقم فاتورة المورد', 'Bill Number'],
      },
      {
        field: 'billDate',
        labelAr: 'تاريخ الفاتورة (YYYY-MM-DD)',
        labelEn: 'Bill Date',
        required: true,
        dataType: 'date',
        example: '2026-03-18',
        descriptionAr: 'تاريخ الفاتورة',
        descriptionEn: 'Bill date in YYYY-MM-DD',
        aliases: ['billDate', 'bill_date', 'date', 'تاريخ الفاتورة', 'التاريخ', 'Bill Date'],
      },
      {
        field: 'supplierVatOrMobile',
        labelAr: 'الرقم الضريبي للمورد أو الجوال',
        labelEn: 'Supplier VAT or Mobile',
        required: true,
        dataType: 'string',
        example: '300045612300003',
        descriptionAr: 'المفتاح التعريفي للمورد في النظام',
        descriptionEn: 'Supplier identifier (VAT ID or mobile phone)',
        aliases: ['supplierVatOrMobile', 'supplierVat', 'supplier_vat', 'الرقم الضريبي للمورد', 'جوال المورد', 'Supplier'],
      },
      {
        field: 'itemSku',
        labelAr: 'رمز الصنف المشترى (SKU)',
        labelEn: 'Item SKU',
        required: true,
        dataType: 'string',
        example: 'ITM-ELEC-101',
        descriptionAr: 'رمز الصنف المشترى من المخزن',
        descriptionEn: 'Catalog Item SKU purchased',
        aliases: ['itemSku', 'sku', 'رمز الصنف', 'كود الصنف', 'Item SKU'],
      },
      {
        field: 'quantity',
        labelAr: 'الكمية المشتراة',
        labelEn: 'Quantity Purchased',
        required: true,
        dataType: 'number',
        example: 10,
        descriptionAr: 'الكمية المستلمة',
        descriptionEn: 'Quantity delivered',
        aliases: ['quantity', 'qty', 'الكمية', 'العدد', 'Quantity'],
      },
      {
        field: 'unitCost',
        labelAr: 'تكلفة الوحدة (ر.س)',
        labelEn: 'Unit Cost (SAR)',
        required: true,
        dataType: 'number',
        example: 950,
        descriptionAr: 'تكلفة شراء الوحدة قبل الضريبة',
        descriptionEn: 'Purchase cost per unit before VAT',
        aliases: ['unitCost', 'unit_cost', 'cost', 'سعر التكلفة', 'سعر الشراء', 'Unit Cost', 'Cost'],
      },
      {
        field: 'vatRate',
        labelAr: 'نسبة الضريبة %',
        labelEn: 'VAT Rate %',
        required: false,
        dataType: 'number',
        example: 15,
        descriptionAr: 'نسبة الضريبة القابلة للخصم',
        descriptionEn: 'Deductible input VAT rate (15%)',
        aliases: ['vatRate', 'vat_rate', 'نسبة الضريبة', 'VAT Rate'],
      },
    ],
    sampleRows: [
      {
        billNumber: 'PB-2026-0045',
        billDate: '2026-03-18',
        supplierVatOrMobile: '300045612300003',
        itemSku: 'ITM-ELEC-101',
        quantity: 10,
        unitCost: 950,
        vatRate: 15,
      },
    ],
  },

  PAYMENTS: {
    template: 'PAYMENTS',
    nameAr: 'سندات القبض والصرف (سداد الأطراف)',
    nameEn: 'Customer Receipts & Supplier Payments',
    category: 'MOVEMENTS',
    descriptionAr: 'استيراد سندات القبض والدفع مع تحديد طريقة الدفع (نقد، بنك، بطاقة) وتحديث حسابات الأطراف',
    descriptionEn: 'Import receipts and payment vouchers with payment tender and balance updates',
    primaryKeyField: 'voucherNumber',
    fields: [
      {
        field: 'voucherNumber',
        labelAr: 'رقم السند',
        labelEn: 'Voucher Number',
        required: true,
        dataType: 'string',
        example: 'RCT-2026-010',
        descriptionAr: 'الرقم الفريد لسند القبض أو الصرف',
        descriptionEn: 'Unique payment voucher number',
        aliases: ['voucherNumber', 'voucher_number', 'رقم السند', 'السند', 'Voucher Number', 'Voucher #'],
      },
      {
        field: 'paymentType',
        labelAr: 'نوع السند (RECEIPT / PAYMENT)',
        labelEn: 'Type (RECEIPT / PAYMENT)',
        required: true,
        dataType: 'string',
        example: 'RECEIPT',
        descriptionAr: 'RECEIPT (قبض من عميل) أو PAYMENT (صرف لمورد)',
        descriptionEn: 'RECEIPT (customer receipt) or PAYMENT (supplier payment)',
        aliases: ['paymentType', 'payment_type', 'type', 'نوع السند', 'Type', 'Voucher Type'],
      },
      {
        field: 'partyVatOrMobile',
        labelAr: 'الرقم الضريبي للطرف أو الجوال',
        labelEn: 'Party VAT or Mobile',
        required: true,
        dataType: 'string',
        example: '300012345600003',
        descriptionAr: 'معرف العميل أو المورد المسجل بالنظام',
        descriptionEn: 'Party VAT ID or mobile phone',
        aliases: ['partyVatOrMobile', 'party', 'الطرف', 'العميل/المورد', 'رقم الطرف', 'Party'],
      },
      {
        field: 'amountSar',
        labelAr: 'المبلغ المدفوع (ر.س)',
        labelEn: 'Amount (SAR)',
        required: true,
        dataType: 'number',
        example: 5000,
        descriptionAr: 'المبلغ المسدد بالريال السعودي',
        descriptionEn: 'Voucher payment amount in SAR',
        aliases: ['amountSar', 'amount', 'المبلغ', 'القيمة', 'Amount', 'Amount (SAR)'],
      },
      {
        field: 'paymentMethod',
        labelAr: 'طريقة الدفع (CASH/BANK/CARD)',
        labelEn: 'Payment Method',
        required: false,
        dataType: 'string',
        example: 'BANK',
        descriptionAr: 'CASH (نقدي)، BANK (تحويل بنكي)، CARD (مدى/بطاقة)',
        descriptionEn: 'CASH, BANK, or CARD',
        aliases: ['paymentMethod', 'payment_method', 'طريقة الدفع', 'طريقة السداد', 'Method', 'Payment Method'],
      },
      {
        field: 'paymentDate',
        labelAr: 'تاريخ السداد (YYYY-MM-DD)',
        labelEn: 'Payment Date',
        required: true,
        dataType: 'date',
        example: '2026-03-21',
        descriptionAr: 'تاريخ عملية الدفع',
        descriptionEn: 'Payment transaction date',
        aliases: ['paymentDate', 'payment_date', 'date', 'تاريخ السند', 'التاريخ', 'Date'],
      },
    ],
    sampleRows: [
      {
        voucherNumber: 'RCT-2026-010',
        paymentType: 'RECEIPT',
        partyVatOrMobile: '300012345600003',
        amountSar: 5000,
        paymentMethod: 'BANK',
        paymentDate: '2026-03-21',
      },
    ],
  },

  JOURNAL_ENTRIES: {
    template: 'JOURNAL_ENTRIES',
    nameAr: 'قيود اليومية العامة (Rule G1)',
    nameEn: 'General Ledger Journal Entries',
    category: 'MOVEMENTS',
    descriptionAr: 'استيراد قيود اليومية المركبة مجمعة برقم القيد مع فرض التوازن التام بين المدين والدائن لكل قيد',
    descriptionEn: 'Import multi-line journal entries grouped by entryNumber with strict debit=credit balance',
    primaryKeyField: 'entryNumber',
    fields: [
      {
        field: 'entryNumber',
        labelAr: 'رقم القيد',
        labelEn: 'Entry Number',
        required: true,
        dataType: 'string',
        example: 'JV-2026-008',
        descriptionAr: 'الرقم التعريفي للقيد (لتجميع سطور القيد الواحد)',
        descriptionEn: 'Unique entry number for grouping journal lines',
        aliases: ['entryNumber', 'entry_number', 'رقم القيد', 'القيد', 'Entry Number', 'JV Number'],
      },
      {
        field: 'entryDate',
        labelAr: 'تاريخ القيد (YYYY-MM-DD)',
        labelEn: 'Entry Date',
        required: true,
        dataType: 'date',
        example: '2026-03-20',
        descriptionAr: 'تاريخ إجراء القيد المحاسبي',
        descriptionEn: 'Posting date of the journal entry',
        aliases: ['entryDate', 'entry_date', 'date', 'تاريخ القيد', 'التاريخ', 'Date'],
      },
      {
        field: 'accountCode',
        labelAr: 'رقم الحساب',
        labelEn: 'Account Code',
        required: true,
        dataType: 'string',
        example: '10101',
        descriptionAr: 'رقم الحساب في دليل الحسابات',
        descriptionEn: 'Account code from chart of accounts',
        aliases: ['accountCode', 'account_code', 'رقم الحساب', 'كود الحساب', 'Account Code'],
      },
      {
        field: 'debitSar',
        labelAr: 'المدين (ر.س)',
        labelEn: 'Debit (SAR)',
        required: false,
        dataType: 'number',
        example: 12000,
        descriptionAr: 'مبلغ المدين',
        descriptionEn: 'Debit amount',
        aliases: ['debitSar', 'debit', 'مدين', 'المدين', 'Debit'],
      },
      {
        field: 'creditSar',
        labelAr: 'الدائن (ر.س)',
        labelEn: 'Credit (SAR)',
        required: false,
        dataType: 'number',
        example: 0,
        descriptionAr: 'مبلغ الدائن',
        descriptionEn: 'Credit amount',
        aliases: ['creditSar', 'credit', 'دائن', 'الدائن', 'Credit'],
      },
      {
        field: 'lineDescription',
        labelAr: 'شرح السطر (البيان)',
        labelEn: 'Line Description',
        required: false,
        dataType: 'string',
        example: 'إثبات مصروف الإيجار الشهري للمقر الرئيسي',
        descriptionAr: 'بيان وتفصيل السطر المحاسبي',
        descriptionEn: 'Journal line narrative description',
        aliases: ['lineDescription', 'description', 'البيان', 'شرح السطر', 'Description'],
      },
    ],
    sampleRows: [
      {
        entryNumber: 'JV-2026-008',
        entryDate: '2026-03-20',
        accountCode: '50101',
        debitSar: 12000,
        creditSar: 0,
        lineDescription: 'إثبات مصروف الإيجار الشهري للمقر',
      },
      {
        entryNumber: 'JV-2026-008',
        entryDate: '2026-03-20',
        accountCode: '10102',
        debitSar: 0,
        creditSar: 12000,
        lineDescription: 'سداد الإيجار من مصرف الراجحي',
      },
    ],
  },

  STOCK_OPENING: {
    template: 'STOCK_OPENING',
    nameAr: 'بضاعة أول المدة وأرصدة المستودعات',
    nameEn: 'Opening Stock & Warehouse Balances',
    category: 'MOVEMENTS',
    descriptionAr: 'استيراد بضاعة أول المدة بالمستودعات مع احتساب تكلفة WAC وتوليد القيد الافتتاحي في حقوق الملكية',
    descriptionEn: 'Import opening stock by warehouse, calculate initial WAC, and post balancing equity journal',
    primaryKeyField: 'documentNumber',
    secondaryKeyFields: ['itemSku', 'warehouseCode'],
    fields: [
      {
        field: 'documentNumber',
        labelAr: 'رقم وثيقة الجرد الافتتاحي',
        labelEn: 'Document Number',
        required: true,
        dataType: 'string',
        example: 'OPN-WH-001',
        descriptionAr: 'رقم وثيقة بضاعة أول المدة لتجميع الأصناف',
        descriptionEn: 'Opening stock batch document number',
        aliases: ['documentNumber', 'doc_number', 'رقم الوثيقة', 'رقم السند', 'Document #', 'Document Number'],
      },
      {
        field: 'warehouseCode',
        labelAr: 'رمز المستودع',
        labelEn: 'Warehouse Code',
        required: true,
        dataType: 'string',
        example: 'WH-RYD-01',
        descriptionAr: 'رمز المستودع المسجل في النظام',
        descriptionEn: 'Valid warehouse code (e.g. WH-RYD-01 or WH-01)',
        aliases: ['warehouseCode', 'warehouse', 'رمز المستودع', 'المستودع', 'كود المستودع', 'Warehouse Code'],
      },
      {
        field: 'itemSku',
        labelAr: 'رمز الصنف (SKU)',
        labelEn: 'Item SKU',
        required: true,
        dataType: 'string',
        example: 'ITM-ELEC-101',
        descriptionAr: 'رمز الصنف في المخزن',
        descriptionEn: 'Catalog item SKU code',
        aliases: ['itemSku', 'sku', 'رمز الصنف', 'كود الصنف', 'Item SKU', 'SKU'],
      },
      {
        field: 'quantity',
        labelAr: 'الكمية المتوفرة',
        labelEn: 'Opening Quantity',
        required: true,
        dataType: 'number',
        example: 50,
        descriptionAr: 'كمية بضاعة أول المدة في المستودع',
        descriptionEn: 'Opening stock count in base unit',
        aliases: ['quantity', 'qty', 'الكمية', 'رصيد أول المدة', 'Opening Qty', 'Quantity'],
      },
      {
        field: 'unitCost',
        labelAr: 'تكلفة الوحدة (ر.س)',
        labelEn: 'Unit Cost (SAR)',
        required: true,
        dataType: 'number',
        example: 950,
        descriptionAr: 'تكلفة تقييم الوحدة في بضاعة أول المدة',
        descriptionEn: 'Valuation cost per unit in SAR',
        aliases: ['unitCost', 'unit_cost', 'cost', 'سعر التكلفة', 'تكلفة الحبة', 'Unit Cost', 'Cost'],
      },
    ],
    sampleRows: [
      {
        documentNumber: 'OPN-WH-001',
        warehouseCode: 'WH-RYD-01',
        itemSku: 'ITM-ELEC-101',
        quantity: 50,
        unitCost: 950,
      },
      {
        documentNumber: 'OPN-WH-001',
        warehouseCode: 'WH-RYD-01',
        itemSku: 'ITM-ELEC-102',
        quantity: 120,
        unitCost: 180,
      },
    ],
  },
};
