import { DocumentType, DocumentDataPayload } from './types.js';

export const SAMPLE_COMPANY_INFO = {
  nameAr: 'شركة قمة النماء للتجارة والتقنية (ش.م.م)',
  nameEn: 'Qimmat Al-Namaa Trading & Tech Co. (LLC)',
  vatNumber: '310123456700003',
  crNumber: '1010987654',
  nationalAddress: '7245 طريق الملك فهد - حي العليا - الرياض 12214 - المملكة العربية السعودية',
  phone: '+966 11 456 7890',
  email: 'billing@alnamaa.sa',
  logoUrl: '',
  bankAccounts: [
    { bankName: 'مصرف الراجحي (Al Rajhi Bank)', iban: 'SA0380000123456789012345', accountName: 'شركة قمة النماء للتجارة' },
    { bankName: 'البنك الأهلي السعودي (SNB)', iban: 'SA4410000098765432109876', accountName: 'شركة قمة النماء للتجارة' },
  ],
};

export const SAMPLE_DOCUMENTS: Record<DocumentType, DocumentDataPayload> = {
  SALES_INVOICE: {
    documentType: 'SALES_INVOICE',
    documentId: 'inv-sample-001',
    documentNumber: 'INV-2026-0042',
    issueDate: '2026-09-19',
    dueDate: '2026-10-19',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'مؤسسة أفق التقنية للتجارة',
      nameEn: 'Ofuq Tech Trading Est.',
      vatNumber: '300987654300003',
      crNumber: '1010543210',
      address: 'شارع التحلية - السليمانية - الرياض',
      phone: '+966 50 123 4567',
      email: 'finance@ofuq-tech.sa',
      partyType: 'CUSTOMER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'PRD-LTP-01',
        nameAr: 'خادم حوسبة مؤسسي Dell PowerEdge R750',
        nameEn: 'Dell PowerEdge R750 Server',
        quantity: 2,
        unitName: 'وحدة (Unit)',
        unitPriceSar: 12500,
        discountSar: 500,
        subtotalSar: 24500,
        vatRatePct: 15,
        vatAmountSar: 3675,
        totalSar: 28175,
        barcode: '6281000010012',
      },
      {
        lineNumber: 2,
        itemCode: 'SRV-INST-01',
        nameAr: 'خدمات التركيب والتهيئة البرمجية السحابية',
        nameEn: 'Cloud Installation & Setup Services',
        quantity: 1,
        unitName: 'خدمة (Service)',
        unitPriceSar: 3000,
        discountSar: 0,
        subtotalSar: 3000,
        vatRatePct: 15,
        vatAmountSar: 450,
        totalSar: 3450,
        barcode: '6281000010029',
      },
    ],
    totals: {
      subtotalExclVatSar: 28000,
      discountTotalSar: 500,
      taxableAmountSar: 27500,
      vatAmountSar: 4125,
      totalAmountSar: 31625,
      paidAmountSar: 0,
      balanceDueSar: 31625,
    },
    zatca: {
      qrCodeBase64: 'AQ3YtNixa2HZhSDZgtmF2Kkg2KfZhNmG2YXYp9ihAg8zMTAxMjM0NTY3MDAwMDMDEDIwMjYtMDktMTlUMTI6MDA6MDBaBAYzMTYyNS4wMAUFNDEyNS4wMA==',
      invoiceHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      invoiceTypeCode: '388',
      isSimplified: false,
    },
    notes: 'شكراً لتعاملكم معنا. الدفع خلال 30 يوماً من تاريخ الفاتورة بموجب الشروط التجارية المعتمدة.',
    terms: 'تعتبر هذه الفاتورة ضريبية رسمية بموجب أنظمة هيئة الزكاة والضريبة والجمارك (ZATCA).',
  },

  PURCHASE_BILL: {
    documentType: 'PURCHASE_BILL',
    documentId: 'bill-sample-001',
    documentNumber: 'BILL-2026-0018',
    issueDate: '2026-09-15',
    dueDate: '2026-10-15',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'شركة المورد الأول للإلكترونيات المحدودة',
      nameEn: 'Al-Mawrid Electronics Ltd.',
      vatNumber: '310555444300003',
      crNumber: '1010112233',
      address: 'المنطقة الصناعية الثانية - الرياض',
      phone: '+966 11 223 3445',
      email: 'sales@almawrid-el.sa',
      partyType: 'SUPPLIER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'RAW-SWT-08',
        nameAr: 'مفاتيح شبكات Cisco Catalyst 9300',
        nameEn: 'Cisco Catalyst 9300 Switches',
        quantity: 4,
        unitName: 'حبة (Pcs)',
        unitPriceSar: 6200,
        discountSar: 200,
        subtotalSar: 24600,
        vatRatePct: 15,
        vatAmountSar: 3690,
        totalSar: 28290,
      },
    ],
    totals: {
      subtotalExclVatSar: 24800,
      discountTotalSar: 200,
      taxableAmountSar: 24600,
      vatAmountSar: 3690,
      totalAmountSar: 28290,
      paidAmountSar: 10000,
      balanceDueSar: 18290,
    },
    notes: 'تمت مطابقة الفاتورة مع أمر الشراء PO-2026-0035 ومذكرة استلام البضاعة GRN-2026-0012.',
  },

  QUOTATION: {
    documentType: 'QUOTATION',
    documentId: 'quot-sample-001',
    documentNumber: 'QUOT-2026-0089',
    issueDate: '2026-09-18',
    dueDate: '2026-10-18',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'شركة الحلول المبتكرة للاستشارات',
      nameEn: 'Innovative Solutions Consulting',
      vatNumber: '311222333400003',
      crNumber: '1010443322',
      address: 'طريق الأمير محمد بن عبدالعزيز - الرياض',
      phone: '+966 55 998 8776',
      email: 'procure@innovativesol.sa',
      partyType: 'CUSTOMER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'LIC-ERP-ENT',
        nameAr: 'تراخيص نظام تخطيط الموارد ERP السحابي (اشتراك سنوي)',
        nameEn: 'Cloud ERP Enterprise Annual Licenses',
        quantity: 10,
        unitName: 'مستخدم (User)',
        unitPriceSar: 1800,
        discountSar: 1800,
        subtotalSar: 16200,
        vatRatePct: 15,
        vatAmountSar: 2430,
        totalSar: 18630,
      },
    ],
    totals: {
      subtotalExclVatSar: 18000,
      discountTotalSar: 1800,
      taxableAmountSar: 16200,
      vatAmountSar: 2430,
      totalAmountSar: 18630,
      paidAmountSar: 0,
      balanceDueSar: 18630,
    },
    notes: 'عرض السعر سارٍ لمدة 30 يوماً من تاريخ إصداره.',
    terms: 'الأسعار تشمل الدعم الفني والتحديثات الدورية لمدة عام كامل.',
  },

  SALES_ORDER: {
    documentType: 'SALES_ORDER',
    documentId: 'so-sample-001',
    documentNumber: 'SO-2026-0055',
    issueDate: '2026-09-17',
    dueDate: '2026-09-30',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'مؤسسة أفق التقنية للتجارة',
      nameEn: 'Ofuq Tech Trading Est.',
      vatNumber: '300987654300003',
      partyType: 'CUSTOMER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'ITM-CAB-01',
        nameAr: 'كبائن شبكات خوادم 42U مع وحدات تبريد',
        quantity: 2,
        unitName: 'طقم (Set)',
        unitPriceSar: 4500,
        discountSar: 0,
        subtotalSar: 9000,
        vatRatePct: 15,
        vatAmountSar: 1350,
        totalSar: 10350,
      },
    ],
    totals: {
      subtotalExclVatSar: 9000,
      discountTotalSar: 0,
      taxableAmountSar: 9000,
      vatAmountSar: 1350,
      totalAmountSar: 10350,
    },
    notes: 'أمر بيع مؤكد. موعد التسليم المتوقع مستودع الرياض الرئيسي.',
  },

  PURCHASE_ORDER: {
    documentType: 'PURCHASE_ORDER',
    documentId: 'po-sample-001',
    documentNumber: 'PO-2026-0044',
    issueDate: '2026-09-14',
    dueDate: '2026-09-28',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'شركة التوريدات العالمية المحدودة',
      vatNumber: '310999888700003',
      partyType: 'SUPPLIER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'NET-FBR-100',
        nameAr: 'كيابل ألياف بصرية أحادية النمط 100 متر',
        quantity: 20,
        unitName: 'لفة (Roll)',
        unitPriceSar: 350,
        discountSar: 0,
        subtotalSar: 7000,
        vatRatePct: 15,
        vatAmountSar: 1050,
        totalSar: 8050,
      },
    ],
    totals: {
      subtotalExclVatSar: 7000,
      discountTotalSar: 0,
      taxableAmountSar: 7000,
      vatAmountSar: 1050,
      totalAmountSar: 8050,
    },
    notes: 'يرجى إرفاق شهادة المنشأ وضمان الجودة مع الشحنة.',
  },

  RECEIPT_VOUCHER: {
    documentType: 'RECEIPT_VOUCHER',
    documentId: 'rv-sample-001',
    documentNumber: 'RV-2026-0120',
    issueDate: '2026-09-18',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'مؤسسة أفق التقنية للتجارة',
      nameEn: 'Ofuq Tech Trading Est.',
      vatNumber: '300987654300003',
      partyType: 'CUSTOMER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'ALLOC-INV-0040',
        nameAr: 'دفعة سداد عن فاتورة مبيعات INV-2026-0040',
        quantity: 1,
        unitName: 'سند (Voucher)',
        unitPriceSar: 15000,
        discountSar: 0,
        subtotalSar: 15000,
        vatRatePct: 0,
        vatAmountSar: 0,
        totalSar: 15000,
      },
    ],
    totals: {
      subtotalExclVatSar: 15000,
      discountTotalSar: 0,
      taxableAmountSar: 15000,
      vatAmountSar: 0,
      totalAmountSar: 15000,
      paidAmountSar: 15000,
      balanceDueSar: 0,
    },
    paymentInfo: {
      method: 'تحويل بنكي - مصرف الراجحي (Bank Transfer)',
      referenceNumber: 'TRX-9823471029',
      allocations: [{ documentNumber: 'INV-2026-0040', amountSar: 15000 }],
    },
    notes: 'استلمنا من مؤسسة أفق التقنية مبلغ وقدره خمسة عشر ألف ريال سعودي لا غير.',
  },

  PAYMENT_VOUCHER: {
    documentType: 'PAYMENT_VOUCHER',
    documentId: 'pv-sample-001',
    documentNumber: 'PV-2026-0095',
    issueDate: '2026-09-16',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'شركة المورد الأول للإلكترونيات المحدودة',
      vatNumber: '310555444300003',
      partyType: 'SUPPLIER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'ALLOC-BILL-0015',
        nameAr: 'سداد مستحقات فاتورة مشتريات BILL-2026-0015',
        quantity: 1,
        unitName: 'سند (Voucher)',
        unitPriceSar: 10000,
        discountSar: 0,
        subtotalSar: 10000,
        vatRatePct: 0,
        vatAmountSar: 0,
        totalSar: 10000,
      },
    ],
    totals: {
      subtotalExclVatSar: 10000,
      discountTotalSar: 0,
      taxableAmountSar: 10000,
      vatAmountSar: 0,
      totalAmountSar: 10000,
      paidAmountSar: 10000,
      balanceDueSar: 0,
    },
    paymentInfo: {
      method: 'حوالة مصرفية سريعة (SARIE)',
      referenceNumber: 'SARIE-20260916001',
    },
    notes: 'تم صرف المبلغ خصماً من حساب بنك الرياض الرئيسي.',
  },

  CREDIT_NOTE: {
    documentType: 'CREDIT_NOTE',
    documentId: 'cn-sample-001',
    documentNumber: 'CN-2026-0008',
    issueDate: '2026-09-19',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'مؤسسة أفق التقنية للتجارة',
      vatNumber: '300987654300003',
      partyType: 'CUSTOMER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'PRD-LTP-01',
        nameAr: 'إرجاع جهاز خادم حوسبة مؤسسي لوجود تلف بالمروحة',
        quantity: 1,
        unitName: 'وحدة (Unit)',
        unitPriceSar: 12500,
        discountSar: 250,
        subtotalSar: 12250,
        vatRatePct: 15,
        vatAmountSar: 1837.5,
        totalSar: 14087.5,
      },
    ],
    totals: {
      subtotalExclVatSar: 12500,
      discountTotalSar: 250,
      taxableAmountSar: 12250,
      vatAmountSar: 1837.5,
      totalAmountSar: 14087.5,
    },
    zatca: {
      qrCodeBase64: 'AQ3YtNixa2HZhSDZgtmF2Kkg2KfZhNmG2YXYp9ihAg8zMTAxMjM0NTY3MDAwMDMDEDIwMjYtMDktMTlUMTM6MDA6MDBaBAYxNDA4Ny41MAUFMTgzNy41MA==',
      invoiceHash: 'f4b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b999',
      invoiceTypeCode: '381',
    },
    notes: 'إشعار دائن صادر لتعديل الفاتورة الضريبية INV-2026-0042 بموجب المادة 54 من اللائحة التنفيذية لضريبة القيمة المضافة.',
  },

  DEBIT_NOTE: {
    documentType: 'DEBIT_NOTE',
    documentId: 'dn-sample-001',
    documentNumber: 'DN-2026-0004',
    issueDate: '2026-09-17',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'شركة المورد الأول للإلكترونيات المحدودة',
      vatNumber: '310555444300003',
      partyType: 'SUPPLIER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'RAW-SWT-08',
        nameAr: 'مردودات مشتريات غير مطابقة للمواصفات',
        quantity: 1,
        unitName: 'حبة (Pcs)',
        unitPriceSar: 6200,
        discountSar: 50,
        subtotalSar: 6150,
        vatRatePct: 15,
        vatAmountSar: 922.5,
        totalSar: 7072.5,
      },
    ],
    totals: {
      subtotalExclVatSar: 6200,
      discountTotalSar: 50,
      taxableAmountSar: 6150,
      vatAmountSar: 922.5,
      totalAmountSar: 7072.5,
    },
    notes: 'إشعار مدين للمورد بموجب فاتورة الشراء الأصلية BILL-2026-0018.',
  },

  CUSTOMER_STATEMENT: {
    documentType: 'CUSTOMER_STATEMENT',
    documentId: 'stmt-sample-001',
    documentNumber: 'STMT-CUST-2026-09',
    issueDate: '2026-09-19',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'مؤسسة أفق التقنية للتجارة',
      nameEn: 'Ofuq Tech Trading Est.',
      vatNumber: '300987654300003',
      phone: '+966 50 123 4567',
      partyType: 'CUSTOMER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'INV-2026-0022',
        nameAr: 'فاتورة مبيعات - أجهزة حاسب آلي',
        quantity: 1,
        unitName: 'فاتورة',
        unitPriceSar: 45000,
        discountSar: 0,
        subtotalSar: 45000,
        vatRatePct: 15,
        vatAmountSar: 6750,
        totalSar: 51750,
      },
      {
        lineNumber: 2,
        itemCode: 'RV-2026-0078',
        nameAr: 'سند قبض - دفعة بنكية حوالة',
        quantity: 1,
        unitName: 'سند',
        unitPriceSar: -30000,
        discountSar: 0,
        subtotalSar: -30000,
        vatRatePct: 0,
        vatAmountSar: 0,
        totalSar: -30000,
      },
      {
        lineNumber: 3,
        itemCode: 'INV-2026-0042',
        nameAr: 'فاتورة مبيعات - خوادم وشبكات',
        quantity: 1,
        unitName: 'فاتورة',
        unitPriceSar: 27500,
        discountSar: 0,
        subtotalSar: 27500,
        vatRatePct: 15,
        vatAmountSar: 4125,
        totalSar: 31625,
      },
    ],
    totals: {
      subtotalExclVatSar: 42500,
      discountTotalSar: 0,
      taxableAmountSar: 42500,
      vatAmountSar: 10875,
      totalAmountSar: 53375,
      paidAmountSar: 30000,
      balanceDueSar: 53375,
    },
    notes: 'رصيد الحساب الحالي المستحق حتى تاريخه: 53,375.00 ريال سعودي. يرجى المبادرة بالسداد.',
  },

  SUPPLIER_STATEMENT: {
    documentType: 'SUPPLIER_STATEMENT',
    documentId: 'stmt-sup-001',
    documentNumber: 'STMT-SUP-2026-09',
    issueDate: '2026-09-19',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    party: {
      nameAr: 'شركة المورد الأول للإلكترونيات المحدودة',
      vatNumber: '310555444300003',
      partyType: 'SUPPLIER',
    },
    lines: [
      {
        lineNumber: 1,
        itemCode: 'BILL-2026-0015',
        nameAr: 'فاتورة توريد كابلات وأجهزة شبكات',
        quantity: 1,
        unitName: 'فاتورة',
        unitPriceSar: 32000,
        discountSar: 0,
        subtotalSar: 32000,
        vatRatePct: 15,
        vatAmountSar: 4800,
        totalSar: 36800,
      },
      {
        lineNumber: 2,
        itemCode: 'PV-2026-0095',
        nameAr: 'سند صرف وسداد بنكي',
        quantity: 1,
        unitName: 'سند',
        unitPriceSar: -10000,
        discountSar: 0,
        subtotalSar: -10000,
        vatRatePct: 0,
        vatAmountSar: 0,
        totalSar: -10000,
      },
    ],
    totals: {
      subtotalExclVatSar: 22000,
      discountTotalSar: 0,
      taxableAmountSar: 22000,
      vatAmountSar: 4800,
      totalAmountSar: 26800,
      paidAmountSar: 10000,
      balanceDueSar: 26800,
    },
    notes: 'كشف حساب الذمم الدائنة المعتمد لدى إدارة الحسابات المالية.',
  },

  BARCODE_LABEL: {
    documentType: 'BARCODE_LABEL',
    documentId: 'lbl-sample-001',
    documentNumber: 'LBL-6281000010012',
    issueDate: '2026-09-19',
    currency: 'SAR',
    company: SAMPLE_COMPANY_INFO,
    lines: [
      {
        lineNumber: 1,
        itemCode: 'PRD-LTP-01',
        nameAr: 'خادم حوسبة مؤسسي Dell PowerEdge R750',
        nameEn: 'Dell PowerEdge R750 Server',
        quantity: 1,
        unitName: 'وحدة',
        unitPriceSar: 12500,
        discountSar: 0,
        subtotalSar: 12500,
        vatRatePct: 15,
        vatAmountSar: 1875,
        totalSar: 14375,
        barcode: '6281000010012',
      },
    ],
    totals: {
      subtotalExclVatSar: 12500,
      discountTotalSar: 0,
      taxableAmountSar: 12500,
      vatAmountSar: 1875,
      totalAmountSar: 14375,
    },
    zatca: {
      qrCodeBase64: 'AQ3YtNixa2HZhSDZgtmF2Kkg2KfZhNmG2YXYp9ihAg8zMTAxMjM0NTY3MDAwMDMDEDIwMjYtMDktMTlUMTI6MDA6MDBaBAYxNDM3NS4wMAUFMTg3NS4wMA==',
    },
    notes: 'السعر شامل ضريبة القيمة المضافة 15%',
  },
};
